include(
    ":app",
    ":libraries:test-utils",
    ":libraries:data",
    ":libraries:domain",
    ":libraries:core",
    ":features:account",
    ":features:notification",
    ":features:favorites"
)
